services:
         app: 
                build: .
                ports:
                        - 1234:8000
                networks:
                              - simulations
networks:
        simulations:
                driver: bridge
